version: "3.7"
services:
    db:
        image: postgres:15.10
        container_name: postgres-dev-9c32
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - 5432:5432
